Sk ja empty pages
Code-4-Community/vsc pull request #9
Opened 2022-01-31 22:24 UTC by saahilkumar

Closes #1 

- Added three new empty pages
  - Login -- `/login`
  - What's New -- `/whatsnew`
  - Contact Us -- `/contact`
- Created an unstyled NavBar component that links between these three pages 

**Question:** Should we add the NavBar to the main page (`index.tsx`)? Right now, it's only on the three new pages.

Here's a screenshot of the Contact Us page for example:

<img width="1680" alt="Screen Shot 2022-01-31 at 5 15 15 PM" src="https://user-images.githubusercontent.com/60633758/151882136-d8ad301a-8319-45eb-9245-42d84f1c7335.png">

2022-01-31 22:41 UTC, rymaju approved these changes
Looks good but I think there are some minor formatting issues, are you sure you ran prettier?

2022-01-31 22:41 UTC, rymaju commented on lib/components/navbar/NavLink.tsx
> +        props.router.pathname === props.path ? "active" : ""
📌 This is interesting, although we will eventually want to replace this with Chakra UI components

2022-01-31 22:41 UTC, rymaju commented on lib/components/navbar/links.tsx
> +const navLinks = [
👍 I like this!

2022-01-31 22:41 UTC, rymaju commented on pages/contact/index.tsx
> +      <NavBar navLinks={navLinks} />
❓ This looks suspiciously not formatted correctly, seems like we want another level of indentation on this line. Did you run prettier?

2022-01-31 23:46 UTC, rymaju commented
![image](https://user-images.githubusercontent.com/23691775/151891506-6b26f008-0a1f-49b6-98e4-295c766b41db.png)
This is what I got from `npm prepush:fix`, looks like there are a couple things to fix, as well as some existing things that got picked up from prettier.

Not sure how that got skipped on your end? Do you get this too? @saahilkumar ?

2022-01-31 23:52 UTC, saahilkumar commented
> Not sure how that got skipped on your end? Do you get this too? @saahilkumar ?

No I didn't see that on my end D: might be a node version thing because I don't think I updated to 17.3.0 yet

2022-02-01 00:24 UTC, rymaju commented
hmm weird, I can fix it for you for now

2022-02-01 02:57 UTC, varunthakkar1 commented on lib/components/navbar/links.tsx
> +const navLinks = [
This is super smart, love it!

2022-02-01 02:58 UTC, varunthakkar1 approved these changes
LGTM! Nice work, just address comments please 👍🏾

2022-02-22 01:51 UTC, saahilkumar commented
@rymaju @varunthakkar1

I replaced `props` with `props: any` in a few different places to get rid of the build errors. Is that chill or is that bad style?

2022-02-22 02:01 UTC, rymaju commented
any is considered harmful 😠

we 'never' talk to him anymore, its like hes someone totally different -- completely 'unknown'

Nobody else will think that was funny but I find my own typescript puns absolutely hilarious

2022-02-22 02:02 UTC, rymaju commented
We want to declare the actual type of props and then use that instead of any, I can find an example somewhere... or you can take a look at the other frontend components in other projects yourself

2022-02-22 02:07 UTC, rymaju commented
Heres an example: https://github.com/Code-4-Community/jpal-frontend/blob/master/src/components/survey/ConfirmAssignments.tsx

2022-02-22 03:13 UTC, rymaju requested changes
😓 Sorry I looked through this and realized I have a lot more questions, maybe we can hop on a call to go over everything? @saahilkumar @ja0911

2022-02-22 03:13 UTC, rymaju commented on lib/components/navbar/index.tsx
> +const NavBar = (props: any) => (
```suggestion
const NavBar: React.FC<NabBarProps> = ({navLinks}) => (
```

2022-02-22 03:13 UTC, rymaju commented on lib/components/navbar/index.tsx
> +    {props.navLinks.map((button: any) => (
🔧 This should have a type! Is it something like:
```ts
type NavBarButton = {
    path: string,
    label: string
}
```
?

2022-02-22 03:13 UTC, rymaju commented on lib/components/navbar/links.tsx
> +const navLinks = [
Ah, this is where you want to define and export your NavBar types

2022-02-22 03:13 UTC, rymaju commented on lib/components/navbar/NavLink.tsx
> +export default withRouter(NavLink);
🤔 Why not use the `useRouter` hook? https://nextjs.org/docs/api-reference/next/router

2022-02-22 03:13 UTC, rymaju commented on lib/components/navbar/NavLink.tsx
> +const NavLink = (props: any) => (
```suggestion
const NavLink : React.FC<NavLinkProps>= ({router, path, label}) => (
```
Or even better, reuse your already defined type:
```suggestion
const NavLink : React.FC<NavBarButton>= ({path, label}) => (
```
and then use `useRouter` in the body of the function.

Or, if you really want to use `withRouter` for some reason:
```suggestion
const NavLink : React.FC<NavBarButton & { NextRouter }>= ({router, path, label}) => (
```
Idk if its called `NextRouter` but you get the gist.

2022-02-22 03:13 UTC, rymaju commented on pages/contact/index.tsx
> +const ContactUs: NextPage = () => {
❓ What is a `NextPage`? Why should we use it over a `React.FC`?

2022-02-24 23:51 UTC, merged